apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: settleup
resources:
  - ../../base
images:
  - name: settleup-api
    newName: settleup-api
    newTag: local
generatorOptions:
  disableNameSuffixHash: true
secretGenerator:
  - name: settleup-secrets
    envs:
      - secrets.env
