apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: settleup
resources:
  - namespace.yaml
  - configmap.yaml
  - api-deployment.yaml
  - api-service.yaml
  - api-hpa.yaml
  - postgres-service.yaml
  - postgres-statefulset.yaml
  - ingress.yaml
